import { act, fireEvent, render } from '@testing-library/react';
import '@testing-library/jest-dom';
import Header from './Header';
import { MemoryRouter } from 'react-router-dom';
import { Translations } from '../../types/translate';

import { LanguageContext } from '../../context/LanguageProvider';
describe('Header component', () => {
  it('renders welcome link and language switcher', () => {
    const translations: Record<string, Translations> = {
      EN: {
        description_text_1: '',
        description_text: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: 'ABOUT',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: '',
        password: '',
        submit_login: '',
        submit_login_2: '',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: '',
        headers: '',
        execute: '',
      },
      RU: {
        description_text: '',
        description_text_1: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: 'О НАС',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: '',
        password: '',
        submit_login: '',
        submit_login_2: '',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: '',
        headers: '',
        execute: '',
      },
    };

    const { getByText } = render(
      <MemoryRouter>
        <LanguageContext.Provider
          value={{ language: 'EN', translations, changeLanguage: () => {} }}
        >
          <Header />
        </LanguageContext.Provider>
      </MemoryRouter>
    );

    expect(getByText('ABOUT')).toBeInTheDocument();
    expect(getByText('EN')).toBeInTheDocument();
  });

  it('renders login and registration buttons when user is not authenticated', () => {
    const translations: Record<string, Translations> = {
      EN: {
        description_text_1: '',
        description_text: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: 'ABOUT',
        main: '',
        signIn: 'SIGN IN',
        signup: 'SIGN UP',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: '',
        password: '',
        submit_login: '',
        submit_login_2: '',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: '',
        headers: '',
        execute: '',
      },
      RU: {
        description_text: '',
        description_text_1: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: 'О НАС',
        main: '',
        signIn: 'ВХОД',
        signup: 'РЕГИСТРАЦИЯ',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: '',
        password: '',
        submit_login: '',
        submit_login_2: '',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: '',
        headers: '',
        execute: '',
      },
    };

    const { getByTestId } = render(
      <MemoryRouter>
        <LanguageContext.Provider
          value={{ language: 'EN', translations, changeLanguage: () => {} }}
        >
          <Header />
        </LanguageContext.Provider>
      </MemoryRouter>
    );

    expect(getByTestId('login-button')).toBeInTheDocument();
    expect(getByTestId('registration-button')).toBeInTheDocument();
  });

  it('navigates to the correct route when link is clicked', async () => {
    const translations: Record<string, Translations> = {
      EN: {
        description_text_1: '',
        description_text: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: 'SIGN OUT',
        welcome: 'ABOUT',
        main: 'MAIN',
        signIn: 'SIGN IN',
        signup: 'SIGN UP',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: '',
        password: '',
        submit_login: '',
        submit_login_2: '',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: '',
        headers: '',
        execute: '',
      },
      RU: {
        description_text: '',
        description_text_1: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: 'ВЫХОД',
        welcome: 'О НАС',
        main: 'ОСНОВНАЯ',
        signIn: 'ВХОД',
        signup: 'РЕГИСТРАЦИЯ',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: '',
        password: '',
        submit_login: '',
        submit_login_2: '',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: '',
        headers: '',
        execute: '',
      },
    };

    const { getByText } = render(
      <MemoryRouter>
        <LanguageContext.Provider
          value={{ language: 'EN', translations, changeLanguage: () => {} }}
        >
          <Header />
        </LanguageContext.Provider>
      </MemoryRouter>
    );
    await act(() => {
      fireEvent.click(getByText('ABOUT'));
      fireEvent.click(getByText('SIGN IN'));
      fireEvent.click(getByText('SIGN UP'));
    });
  });
});
