import { render, fireEvent, screen } from '@testing-library/react';
import SwitchLanguages from './Languages';
import '@testing-library/jest-dom';
import { LanguageContext } from '../../context/LanguageProvider';
import { Translations } from '../../types/translate';

describe('SwitchLanguages component', () => {
  test('renders the language button', () => {
    const translations: Record<string, Translations> = {
      EN: {
        description_text_1: '',
        description_text: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: '',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: 'Email',
        password: 'Password',
        submit_login: 'Login',
        submit_login_2: 'Login with Google',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: 'variables',
        headers: 'headers',
        execute: 'Execute',
      },
      RU: {
        description_text: '',
        description_text_1: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: '',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: 'Электронная почта',
        password: 'Пароль',
        submit_login: 'Войти',
        submit_login_2: 'Войти через Google',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: 'переменные',
        headers: 'заголовоки',
        execute: 'Выполнить',
      },
    };
    render(
      <LanguageContext.Provider
        value={{ language: 'EN', translations, changeLanguage: () => {} }}
      >
        <SwitchLanguages />
      </LanguageContext.Provider>
    );
    const buttonElement = screen.getByText(/EN/i);
    expect(buttonElement).toBeInTheDocument();
  });
});
jest.mock('../../main', () => ({
  useLanguage: () => ({
    language: 'EN',
    changeLanguage: jest.fn(),
  }),
}));
describe('SwitchLanguages', () => {
  test('renders the default language button', () => {
    const translations: Record<string, Translations> = {
      EN: {
        description_text_1: '',
        description_text: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: '',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: 'Email',
        password: 'Password',
        submit_login: 'Login',
        submit_login_2: 'Login with Google',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: 'variables',
        headers: 'headers',
        execute: 'Execute',
      },
      RU: {
        description_text: '',
        description_text_1: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: '',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: 'Электронная почта',
        password: 'Пароль',
        submit_login: 'Войти',
        submit_login_2: 'Войти через Google',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: 'переменные',
        headers: 'заголовоки',
        execute: 'Выполнить',
      },
    };
    const { getByText } = render(
      <LanguageContext.Provider
        value={{ language: 'EN', translations, changeLanguage: () => {} }}
      >
        <SwitchLanguages />
      </LanguageContext.Provider>
    );
    const buttonElement = getByText('EN');
    expect(buttonElement).toBeInTheDocument();
  });

  test('toggles the dropdown when clicked', () => {
    const translations: Record<string, Translations> = {
      EN: {
        description_text_1: '',
        description_text: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: '',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: 'Email',
        password: 'Password',
        submit_login: 'Login',
        submit_login_2: 'Login with Google',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: 'variables',
        headers: 'headers',
        execute: 'Execute',
      },
      RU: {
        description_text: '',
        description_text_1: '',
        description_text_2: '',
        description_text_3: '',
        description_text_4: '',
        description_text_5: '',
        description_text_6: '',
        title: '',
        title_span: '',
        title_1: '',
        signOut: '',
        welcome: '',
        main: '',
        signIn: '',
        signup: '',
        course_description_title: '',
        course_description_text: '',
        course_description_text_1: '',
        course_description_text_2: '',
        course_description_text_3: '',
        course_description_text_4: '',
        course_description_text_5: '',
        course_description_text_6: '',
        course_description_text_7: '',
        course_description_text_8: '',
        about_description_text: '',
        about_description_text_2: '',
        about_description_text_3: '',
        about_title: '',
        about_title_span: '',
        form_login_title: '',
        email: 'Электронная почта',
        password: 'Пароль',
        submit_login: 'Войти',
        submit_login_2: 'Войти через Google',
        firstname: '',
        submit: '',
        submit_2: '',
        back_sign_in: '',
        now: '',
        alert_registration: '',
        validacia_password: '',
        validation_name: '',
        digit: '',
        lowercase: '',
        uppercase: '',
        simbol: '',
        variables: 'переменные',
        headers: 'заголовоки',
        execute: 'Выполнить',
      },
    };
    const { getByText, queryByText } = render(
      <LanguageContext.Provider
        value={{ language: 'EN', translations, changeLanguage: () => {} }}
      >
        <SwitchLanguages />
      </LanguageContext.Provider>
    );
    const buttonElement = getByText('EN'); //EN
    fireEvent.click(buttonElement);
    expect(queryByText('RU'));
    fireEvent.click(buttonElement);
    expect(getByText('EN')).toBeInTheDocument();
  });
});
